title: Moïse Ngos
logo: /asset/img/profil.jpg
description: Étudiant en troisième année d'informatique à Keyce Informatique et Intelligence Artificielle, passionné par l'intelligence artificielle et le Big Data. Motivé par la recherche et le développement de solutions innovantes pour résoudre des problématiques réelles. À la recherche d'experiences pour mettre en application mes compétences en IA et en analyse de données
show_downloads: true
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 
